In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
 #Read all csv in Fiscal_Data_Raw folder 
folder_path = '../Data/FisCal_Data_Raw'
all_files = os.listdir(folder_path)
csv_files = [f for f in all_files if f.endswith('.csv')]

In [3]:
#combine csv files

combined_df = pd.concat(
    [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)

/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)
/var/folders/qy/kq8739gn3vl9c_x_rd1hgthw0000gn/T/ipykernel_47175/3437882423.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(os.path.join(folder_path, f)) for f in csv_files], ignore_index=True)

In [4]:
combined_df.head()

,business_unit,agency_name,department_name,document_id,related_document,accounting_date,fiscal_year_begin,accounting_period,VENDOR_NAME,account,...,fund_description,program_code,program_description,sub_program_description,budget_reference,budget_reference_category,budget_reference_sub_category,budget_reference_description,year_of_enactment,monetary_amount
0,3930,Environmental Protection,Dept of Pesticide Regulation,3930.00042736.0.00013.0005,NaN,2024-09-25,2024,3,WEX BANK,5390870,...,Cannabis Tax Dept Pesticid Reg,3540082000,Enforcement,Pesticide Programs,501,State Operations,Non-Budget Act,Non-BA State Operations-Sup501,2017,2.32
1,954,"Legislative, Judicial, & Exec",Scholarshare Investment Board,0954.00002954.0.00001.0002,NaN,2024-09-26,2024,3,CONFIDENTIAL,5320420,...,Scholarshare Administrative Fu,780000000,Golden St Scholarshare Trust,Golden St Scholarshare Trust,001,State Operations,Budget Act,BA State Operations-Support001,2024,69.34
2,250,"Legislative, Judicial, & Exec",Judicial Branch,0250.00195905.0.00001.0001,NaN,2024-09-12,2024,3,STATE BAR OF CALIFORNIA,5340580,...,CORONAVIRUS FISCAL RECOVERY FD,140010000,Judicial Council,Judicial Council,594,State Operations,Non-Budget Act,Non-BA State Operations-Sup594,2022,26325.66
3,7870,Government Operations,Victim Compensation Board CA,7870.00021273.0.00001.0001,NaN,2024-09-12,2024,3,VCGCB SINGLE PAY,5490000,...,Forced or Involuntary Steril,6380000000,Victim Compensation,Victim Compensation,501,State Operations,Non-Budget Act,Non-BA State Operations-Sup501,2021,15000.00
4,3600,Natural Resources,Department of Fish & Wildlife,3600.00354659.0.00002.0001,NaN,2024-09-19,2024,3,DOWNTOWN FORD SALES,5362295,...,Cannabis Tax Fish Wildlif Allo,2590000000,Biodiversity Conservation Prog,Biodiversity Conservation Prog,530,State Operations,Non-Budget Act,Non-BA State Operations-Sup530,2017,44063.44

In [8]:
# Final_df (spending only from 2023 budget act)
final_df = combined_df[
    (combined_df['budget_reference_sub_category'] == "Budget Act") &
    (combined_df['year_of_enactment'] == 2023)
]

In [9]:
final_df.head()

,business_unit,agency_name,department_name,document_id,related_document,accounting_date,fiscal_year_begin,accounting_period,VENDOR_NAME,account,...,fund_description,program_code,program_description,sub_program_description,budget_reference,budget_reference_category,budget_reference_sub_category,budget_reference_description,year_of_enactment,monetary_amount
10,7503,Government Operations,State Personnel Board,7503.00004576.0.00001.0002,NaN,2024-09-16,2024,3,QUADIENT FINANCE USA INC,5306200,...,General Fund,9999000000,Clearing Account,Clearing Account,001,State Operations,Budget Act,BA State Operations-Support001,2023,4000.00
34,8260,General Government,CA Arts Council,8260.00027270.0.00001.0001,NaN,2024-09-24,2024,3,AMMA FOUNDATION,5432500,...,General Fund,6540000000,Arts Council,Arts Council,101,Local Assistance,Budget Act,BA Local Assistance 101,2023,21250.00
40,2100,"Bus., Consumer Srvcs & Housing",Dept Alcoholic Beverage Cntrl,2100.00124831.0.00001.0001,NaN,2024-09-19,2024,3,CITY OF BANNING,5432000,...,Alcohol Beverages Control Fund,1640019000,Compliance,Administration of the Alcoholi,101,Local Assistance,Budget Act,BA Local Assistance 101,2023,985.65
51,531,"Legislative, Judicial, & Exec",Office of Systems Integration,0531.00032290.0.00001.0001,NaN,2024-09-09,2024,3,KPMG LLP,5340420,...,California Health And Human Se,290000000,Office Of Systems Integration,Office of Systems Integration,001,State Operations,Budget Act,BA State Operations-Support001,2023,560970.00
52,4440,Health and Human Services,Department of State Hospitals,4440.00630034.0.00001.0001,NaN,2024-09-05,2024,3,CONFIDENTIAL,5320210,...,General Fund,4410050000,Patton,State Hospitals,011,State Operations,Budget Act,BA State Operations-Support011,2023,56.00

In [11]:
print(final_df.shape)

(2097844, 26)

In [12]:
#final_df to csv
final_df.to_csv('../Data/Fiscal_Data_Final.csv', index=False)